- .gitignore
- .travis.yml
- databox.hpp
- ports-of-call/portable_arrays.hpp
- test/Makefile.kokkos
- test/test.cpp
A bug in downstream code `singularity-eos` prompted me to run `valgrind` on `Spiner`. I discovered a number of issues with `Spiner`'s pseudo-reference-counting where it tried to manage its own memory on the host but gave up on the device. This design had several problems:
1. It was conceptually difficult to track and bug-prone. 
2. A `DataBox` that managed memory could not go out of scope. If it did, all `DataBox`es that depended on it would be pointing at unitialized memory.
I therefore re-design `DataBox` memory management in this PR. I do the following:
1. `DataBox`es can *allocate* memory. They free memory before re-allocating, but otherwise never free memory.
2. Freeing memory must be performed externally via the `DataBox::finalize()` or `free(DataBox&)` methods, which release …
> Refactor of memory management

- databox.hpp
- ports-of-call/portability.hpp
- test/Makefile.kokkos
- test/test.cpp
For `singularity-opac`, I need the capability to perform interpolation of the form:
```C++
Real v = db.interpToReal(x4, x3, x2, j, x1)
```
where `x1`, `x2`, `x3`, and `x4` are real numbers that are interpolated on and `j` is an integer that's indexed on. This is a common pattern for multi-species transport such as neutrino transport. I don't expect it's needed outside of neutrino transport, but you never know.
> More interpolation operations

- cmake/Format.cmake
- doc/sphinx/src/building.rst
This resolves an issue with in-tree builds, where multiple make format targets may be defined, and cause cmake errors. The simple solution is to namespace the format target. I will apply the same fix to `singularity-eos`.
> namespace formatting

- .gitlab-ci.yml
- CMakeLists.txt
The CI was failing because Spiner was using its own portability settings, rather than let `ports-of-call` handle it. This fixes that issue.
> Let ports of call do its own portability settings

- test/CMakeLists.txt
Small CMake fix needed to get `make convergence` to run. I think the numpy/matplotlib check was actually failing before due to a misnamed variable, but it looked like it was passing because the `MATPLOTLIB_FOUND` check was accepting a return code of 1 as a "pass".
The original error was:  `/bin/sh: plot_convergence.py: command not found`.
> [JOSS REVIEW] Fix plotting convergence

- CMakeLists.txt
Comments out `export(PACKAGE ...)`. As of `cmake@3.15`, this is a no-op. Prior versions will populate the user package registry (`~/.cmake`), which can confuse downstream builds. See https://cmake.org/cmake/help/latest/policy/CMP0090.html
> removed `export(PACKAGE)`

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- cmake/Format.cmake
- installtest/libtest.cpp
- test/test.cpp
@ktsai7 pointed out a test was failing on Power9s. @rbberger found that the reason was that we are using an older Kokkos on that system, and it doesn't support `cuda-relaxed-constexpr`. The test relied on this to move a `std::array` to device via lambda capture.
This change removes the need for that, by instead using a `Kokkos::View`. I also got annoyed waiting for 1e9 points to be evaluated, so I reduce to 1e6 points.
> kokkos test support older kokkos

- doc/sphinx/src/databox.rst
- doc/sphinx/src/getting-started.rst
- doc/sphinx/src/interpolation.rst
- spiner/databox.hpp
- spiner/interpolation.hpp
- test/benchmark.cpp
- test/convergence.cpp
- test/test.cpp
The use case of mixed-precision computing has been suggested. This PR attempts to support that need by templating `Spiner` functionality on underlying data type. This means the following are all valid:
```C++
Spiner::DataBox<float> db(3, 2, 1);
Spiner::DataBox<double> db(5, 4, 3);
Spiner::DataBox<long double> db(55);
```
Any arithmetic type is supported, although I've only tested carefully with floating-point types. Also HDF5 is only supported for `float` and `double` at this time.
I've pinged a few people using spiner downstream. @jdolence @chadmeyer @dholladay00 @jhp-lanl and @brryan do you see this breaking anything you're doing with spiner? Is there any design consideration I'm missing here?
> Template on underlying data type

- .gitlab-ci.yml
The CI pipeline was still loading the CUDA 11.4 module.
> CI: upgrade to CUDA 11.6 on power9

- cmake/content.cmake
When used as a submodule downstream, the build would get unruly about `ports-of-call` target being included twice. This PR inserts a per-package flag that is set when a requested target is already defined in the build, and this flag prevents doing a `fetch + add_subdirectory` that was triggering the error. This logic extends to also prevent `find_package` from triggering.
Originally, the CMake code currently deployed in `spiner` was meant to interact with a similar system up/downstream that would "globally" handle situations like these, as is done in `cmake@3.24` and later releases. However, this ended up being a challenge to develop across project boundaries, and a decision was made to just wait for consuming codes to get up to speed with `cmake@3.24+`, which will provide this …
> Fix "already present target" error when using submodules 

- .github/workflows/tests.yml
- .gitlab-ci.yml
- CMakeLists.txt
- cmake/spinerConfig.cmake.in
- spack-repo/packages/spiner/package.py
1.) Change from `BUILD_TESTING` to `SPINER_BUILD_TESTS`
2.) Ensure `SPINER_USE_HDF` is exported when doing standalone install
3.) Turn down cmake version
4.) Spackage dependency to propagate `main` version to `ports-of-call`
This is a requirement for https://github.com/lanl/singularity-eos/pull/246
> Changes to spackage, CMake export config

- .github/workflows/deps.yml
- .github/workflows/docs.yml
- .github/workflows/formatting.yml
This adds a manual and scheduled action to check for changes in ports-of-call spackages and migrate them over to Spiner. If a change is detected, it will create a PR authored by a bot.
> Add GitHub action to update spackages 🤖 

- spiner/databox.hpp
Even with only host context, it turns out `Kokkos::Malloc` and `Kokkos::Free` are not just the standard `malloc` and `free`. What this means is that if you build Spiner with `Kokkos` backend but no device, it's still dangerous to mix `PORTABLE_MALLOC` with `free`. This was causing a segfault in this particular edge case. Now fixed.
In the long term, to catch such things, we should probably add a Kokkos serial build to the Spiner CI. I didn't bother for now though.
> fix getondevice

- spack-repo/packages/spiner/package.py
Use CMake 3.19 as minimum for latest `spiner` version
> Reduce minimum CMake required

- spiner/databox.hpp
- test/test.cpp
@chadmeyer noticed that `GetOnDevice` on an empty `DataBox` causes an assertion error related to array sizes. I think this was indicating an edge case in `GetOnDevice`: the edge case being being that `GetOnDevice` was attempting to copy memory to device even for unallocated `DataBox`es containing no memory.
This PR simply adds a little default code making `GetOnDevice` a no-op for empty `DataBox`es.
> resolve get on device edge case

- .gitlab-ci.yml
- spack-repo/packages/spiner/package.py
- test/CMakeLists.txt
- test/test.cpp
Update to spack2 v3. This involves updating the spackage, as well as updating the cmake.
> update spack2 v2 to spack2 v3

- .gitlab-ci.yml
> ci: remove power9 and add a100 build

- .gitlab-ci.yml
The currrent default configuration would pull in `intel-oneapi-mkl` as MKL provider, which causes troubles with `numpy`.
> More CI fixes

- .gitlab-ci.yml
> ci: more fixes

- .gitlab-ci.yml
Spack upstreams are now split up by cluster.
> ci: add TESTING_CLUSTER to PROJECT_SPACK_ROOT

- spiner/piecewise_grid_1d.hpp
- test/test.cpp
In the [piecewise grids MR](https://github.com/lanl/singularity-eos/pull/330) in `singularity-eos`, @chadmeyer raised a concern that piecewise grids are not backwards compatible with old tables. This MR fixes that issue.
> make spiner piecewise grids backwards compatible

- CMakeLists.txt
Bump to C++17. It's finally time @mauneyc-LANL
> enable C++17

- doc/sphinx/src/databox.rst
- spiner/databox.hpp
- spiner/regular_grid_1d.hpp
- test/test.cpp
Using tabulated data in, e.g., MPI Windows for shared memory requires the ability to serialize a ``DataBox`` object into pre-allocated shared memory and to build a new thread-local object around said shared memory, so that the object itself is thread-local but it internally points at a table that lives in shared memory. This PR implements this capability.
This will be needed for the equivalent capability in `Singularity-EOS` and also provides a prototype for how that model and API will look.
> Implement serialization and deserialization

- .gitlab-ci.yml
- .gitlab-ci/config/spack/upstreams.yaml
- .gitlab/build_and_test.sh
- spack-repo/packages/spiner/package.py
> Update GitLab CI

- .gitlab/common.yml
> ci: re-enable hard failures

- .gitlab/common.yml
- test/CMakeLists.txt
> ci: update settings

- spiner/databox.hpp
- test/test.cpp
* Add an overload of the `interpToReal` function to the `Databox` class that takes two interpolation parameters and one index, similar to the overload that takes three interpolation parameters and one index.
* This is intended to support 2D interpolation with a non-interpolatable 3rd index.
> Add 2-parameter, 1-index overload of interpToReal.

- spack-repo/packages/spiner/package.py
Removes `kokkos~shared` requirement which prevented other codes from using Spiner.
> spack: remove ^kokkos~shared requirement

- spiner/databox.hpp
* A recently added interpToReal (by @RyanWollaeger) for databox implemented an incorrect assertion, which is only active in Debug builds.
* The updated assertions for the rank-3, 2-axis interpolation overload has been modified to be similar to the older rank-4, 3-axis interpolation assertions.
> Fix Debug assertion in recently added interpToReal overload (sorry).

- cmake/spinerConfig.cmake.in
`cmake/spinerCMake.config` wouldn't check for `hdf5`,`mpi` targets, which could cause downstream codes to fail the CMake configure stage.
> Update spinerConfig.cmake.in to ensure targets exist downstream

- cmake/spinerConfig.cmake.in
Don't mix `find_package(hdf5)` and `find_package(HDF5)`. Use `find_dependency(HDF5)` for consistency.
> cmake: use HDF5 instead of hdf5 in spinerConfig.cmake for consistency

- CMakeLists.txt
- spack-repo/packages/ports-of-call/package.py
- spack-repo/packages/spiner/package.py
These changes are backwards compatible all the way to v0.23. Since Singularity-EOS already has them, we should just bring this library up-to-date. There is more Spack related changes incoming due to the Package API v2 changes, but that will be its own PR.
> Prepare for Spack v1.0.0
